# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2024-07-09 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_url', models.CharField(max_length=100)),
                ('new_url', models.CharField(blank=True, max_length=100, null=True)),
                ('new_url_code', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
