# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2024-07-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
    ]
