# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2024-08-07 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_url_clicked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='new_url_code',
        ),
        migrations.AlterField(
            model_name='url',
            name='new_url',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
