# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2024-08-07 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_auto_20240807_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='new_url',
        ),
    ]
