# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2024-08-07 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_remove_url_new_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='new_url',
            field=models.CharField(default='', editable=False, max_length=700),
        ),
    ]
