# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2024-08-13 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_url_new_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='old_url',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
